name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

  
    - name: Install Dependencies
      run: |
        cd ./backend
        npm ci

    - name: Build Backend
      run: |
        cd ./backend
        npm run build || echo "No build script, skipping build."

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: |
          ./backend/
          ./backend/node_modules/

  test-backend:
    name: Test Backend
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: ./backend/node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('./backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install Dependencies
      run: |
        cd ./backend
        npm ci

    - name: Run Tests with Coverage
      run: |
        cd ./backend
        npm run test:ci

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: ./backend/coverage/
