name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: ./front/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('./front/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-front-

    - name: Install Dependencies
      run: |
        cd ./front
        npm ci

    - name: Build Application
      run: |
        cd ./front
        npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ./front/build/

  test-frontend:
    name: Test Frontend
    needs: build-front
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: ./front/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('./front/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-front-

    - name: Install Dependencies
      run: |
        cd ./front
        npm ci

    - name: Run Tests with Coverage
      run: |
        cd ./front
        npm run test:ci

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: ./front/coverage/

  sonarcloud-analysis:
    name: SonarCloud Analysis
    needs: test-front
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Dependencies
      run: |
        cd ./front
        npm ci

    - name: Collect Coverage (React-specific)
      run: |
        cd ./front
        npm run test:ci -- --coverage
      env:
        CI: true

    - name: Upload Coverage Report
      run: |
        cp ./front/coverage/lcov.info .

    - name: Run SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=${{ secrets.PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.ORGANIZATION_KEY }} \
          -Dsonar.sources=./04_DevOps_Deploying/primer/frontend \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
